name: Trigger website build on content update

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]


jobs:
  # Trigger tramitit website build and deploy
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger website action
        env:
            ACTION_PAT: ${{ secrets.ACTION_PAT }}
        run : |
            curl -L \
                -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer $ACTION_PAT" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/tramitit/tramitit.github.io/actions/workflows/main.yml/dispatches \
                -d '{"ref":"main"}'